# Generated by Django 5.2.12 on 2026-03-05 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CLOUD', 'Cloud'), ('DSA', 'DSA'), ('JAVA', 'Java'), ('FRONTEND', 'Frontend'), ('DATA', 'Data Science'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('credential_url', models.URLField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
