# Generated by Django 5.2.12 on 2026-03-05 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='STUDENT', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(default=1)),
                ('cgpa', models.FloatField(default=0.0)),
                ('skills', models.TextField(blank=True, help_text='Comma separated skills')),
                ('target_role', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
