# Generated by Django 5.2.12 on 2026-03-05 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('APTITUDE', 'Aptitude'), ('CODING', 'Coding'), ('ENGLISH', 'English'), ('DOMAIN', 'Domain')], default='APTITUDE', max_length=50)),
                ('score', models.IntegerField()),
                ('total', models.IntegerField(default=100)),
                ('percentile', models.FloatField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
