import { useState, useEffect } from 'react';
import { Loader2, CheckCircle, Circle, Target, Brain, FileText, BarChart2, MessageSquare, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';

const CATEGORY_ICONS = {
    'Resume': FileText,
    'Aptitude': BarChart2,
    'Behavioral': MessageSquare,
    'Technical': Brain,
    'Career': Target,
    'Growth': Target,
};

const PRIORITY_COLORS = {
    'High': { border: '#ef4444', badge: '#fee2e2', text: '#dc2626' },
    'Medium': { border: '#f59e0b', badge: '#fef3c7', text: '#d97706' },
    'Low': { border: '#10b981', badge: '#d1fae5', text: '#059669' },
};

export default function Roadmap() {
    const [tasks, setTasks] = useState([]);
    const [metrics, setMetrics] = useState(null);
    const [userInfo, setUserInfo] = useState(null);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        const token = localStorage.getItem('access_token');
        fetch('http://localhost:8000/api/readiness/dashboard-stats/', {
            headers: token ? { 'Authorization': `Bearer ${token}` } : {}
        })
            .then(res => res.json())
            .then(data => {
                if (data.ai_roadmap) {
                    setTasks(data.ai_roadmap.map((t, i) => ({
                        id: i,
                        title: typeof t === 'string' ? t : t.title,
                        category: typeof t === 'string' ? 'AI Suggestion' : t.category,
                        priority: typeof t === 'string' ? (i === 0 ? 'High' : 'Medium') : t.priority,
                    })));
                }
                if (data.metrics) setMetrics(data.metrics);
                if (data.user_info) setUserInfo(data.user_info);
            })
            .catch(err => console.error('Failed to load roadmap', err))
            .finally(() => setIsLoading(false));
    }, []);

    const [done, setDone] = useState({});
    const toggleDone = (id) => setDone(prev => ({ ...prev, [id]: !prev[id] }));

    // Generate a human-readable reason for each task based on real scores
    const getReason = (category) => {
        if (!metrics) return '';
        if (category === 'Resume') return `Resume score: ${metrics.resume_score}%`;
        if (category === 'Aptitude') return `Test score: ${metrics.test_score}%`;
        if (category === 'Behavioral' || category === 'Technical') return `Mock interview avg: ${metrics.interview_score}%`;
        if (category === 'Career' || category === 'Growth') return `Overall readiness: ${metrics.readiness_percentage}%`;
        return '';
    };

    return (
        <div style={{ padding: '0.5rem' }}>
            {/* Header */}
            <div className="page-header" style={{ marginBottom: '2rem' }}>
                <h1 className="page-title">AI Roadmap{userInfo?.name ? ` for ${userInfo.name}` : ''}</h1>
                <p className="page-subtitle">Tasks below are automatically generated by the ML engine based on your <strong>actual resume score ({metrics?.resume_score ?? '…'}%)</strong>, <strong>test score ({metrics?.test_score ?? '…'}%)</strong>, and <strong>mock interview average ({metrics?.interview_score ?? '…'}%)</strong>. Upload a new resume or finish a mock to refresh.</p>
            </div>

            {/* Score Summary Strip */}
            {metrics && (
                <div style={{ display: 'flex', gap: '1rem', marginBottom: '2rem', flexWrap: 'wrap' }}>
                    {[
                        { label: 'Resume Score', value: metrics.resume_score, route: '/resume', color: '#6366f1' },
                        { label: 'Test Score', value: metrics.test_score, route: '/tests', color: '#10b981' },
                        { label: 'Interview Avg', value: metrics.interview_score, route: '/interviews', color: '#f59e0b' },
                        { label: 'Readiness', value: metrics.readiness_percentage, route: '/dashboard', color: '#8b5cf6' },
                    ].map(s => (
                        <Link to={s.route} key={s.label} style={{
                            flex: '1 1 180px',
                            display: 'flex',
                            flexDirection: 'column',
                            gap: '0.25rem',
                            padding: '1rem 1.25rem',
                            background: 'white',
                            borderRadius: '12px',
                            boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
                            borderLeft: `4px solid ${s.color}`,
                            textDecoration: 'none',
                            color: 'inherit',
                            transition: 'box-shadow 0.2s',
                        }}>
                            <span style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', fontWeight: 500 }}>{s.label}</span>
                            <span style={{ fontSize: '1.8rem', fontWeight: 700, color: s.color, lineHeight: 1 }}>{s.value}<span style={{ fontSize: '1rem' }}>%</span></span>
                            <span style={{ fontSize: '0.72rem', color: s.color, display: 'flex', alignItems: 'center', gap: '0.2rem' }}>View <ArrowRight size={10} /></span>
                        </Link>
                    ))}
                </div>
            )}

            {/* Timeline */}
            <div style={{ background: 'white', borderRadius: '16px', padding: '2rem', boxShadow: '0 2px 8px rgba(0,0,0,0.06)' }}>
                <h2 style={{ fontSize: '1.1rem', fontWeight: 600, color: 'var(--text-primary)', marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <Target size={20} style={{ color: 'var(--primary)' }} /> Action Plan
                </h2>

                {isLoading ? (
                    <div style={{ textAlign: 'center', padding: '4rem' }}>
                        <Loader2 className="animate-spin" size={36} style={{ margin: '0 auto', color: 'var(--primary)' }} />
                        <p style={{ color: 'var(--text-secondary)', marginTop: '1rem' }}>Generating your AI roadmap…</p>
                    </div>
                ) : tasks.length === 0 ? (
                    <div style={{ textAlign: 'center', padding: '3rem', color: 'var(--text-secondary)' }}>
                        <Target size={48} style={{ margin: '0 auto 1rem', opacity: 0.3 }} />
                        <p>No roadmap tasks yet. Upload your resume or complete a mock interview to get started!</p>
                    </div>
                ) : (
                    <div style={{ position: 'relative', paddingLeft: '2rem' }}>
                        {/* Vertical line */}
                        <div style={{ position: 'absolute', left: '0.6rem', top: 0, bottom: 0, width: '2px', background: 'var(--border)' }} />

                        {tasks.map((task, idx) => {
                            const Icon = CATEGORY_ICONS[task.category] || Target;
                            const colors = PRIORITY_COLORS[task.priority] || PRIORITY_COLORS['Medium'];
                            const isDone = done[task.id];

                            return (
                                <div key={task.id} style={{ position: 'relative', marginBottom: idx < tasks.length - 1 ? '1.5rem' : 0, cursor: 'pointer' }} onClick={() => toggleDone(task.id)}>
                                    {/* Circle on the line */}
                                    <div style={{
                                        position: 'absolute',
                                        left: '-1.95rem',
                                        top: '0.2rem',
                                        width: '1.2rem',
                                        height: '1.2rem',
                                        borderRadius: '50%',
                                        background: isDone ? '#10b981' : 'white',
                                        border: `2px solid ${isDone ? '#10b981' : colors.border}`,
                                        display: 'flex',
                                        alignItems: 'center',
                                        justifyContent: 'center',
                                        flexShrink: 0,
                                        transition: 'all 0.2s',
                                    }}>
                                        {isDone && <CheckCircle size={10} color="white" />}
                                    </div>

                                    {/* Card */}
                                    <div style={{
                                        background: isDone ? '#f9fafb' : 'white',
                                        border: `1px solid ${isDone ? '#e5e7eb' : colors.border}`,
                                        borderRadius: '10px',
                                        padding: '1rem 1.25rem',
                                        display: 'flex',
                                        alignItems: 'center',
                                        gap: '1rem',
                                        opacity: isDone ? 0.6 : 1,
                                        transition: 'all 0.2s',
                                        boxShadow: isDone ? 'none' : '0 1px 4px rgba(0,0,0,0.06)',
                                    }}>
                                        <div style={{ background: colors.badge, borderRadius: '8px', padding: '0.5rem', flexShrink: 0 }}>
                                            <Icon size={18} style={{ color: colors.text }} />
                                        </div>
                                        <div style={{ flex: 1 }}>
                                            <div style={{ fontWeight: 600, color: 'var(--text-primary)', textDecoration: isDone ? 'line-through' : 'none', fontSize: '0.95rem' }}>{task.title}</div>
                                            <div style={{ display: 'flex', gap: '0.5rem', marginTop: '0.4rem', alignItems: 'center', flexWrap: 'wrap' }}>
                                                <span style={{ fontSize: '0.72rem', background: colors.badge, color: colors.text, padding: '0.1rem 0.5rem', borderRadius: '100px', fontWeight: 600 }}>{task.priority}</span>
                                                <span style={{ fontSize: '0.72rem', color: 'var(--text-secondary)' }}>{task.category}</span>
                                                {getReason(task.category) && <span style={{ fontSize: '0.72rem', color: '#6366f1', background: '#eef2ff', padding: '0.1rem 0.5rem', borderRadius: '100px' }}>Based on: {getReason(task.category)}</span>}
                                            </div>
                                        </div>
                                        {isDone ? <CheckCircle size={18} style={{ color: '#10b981', flexShrink: 0 }} /> : <Circle size={18} style={{ color: '#d1d5db', flexShrink: 0 }} />}
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                )}
            </div>

            <p style={{ textAlign: 'center', fontSize: '0.78rem', marginTop: '1.5rem', color: 'var(--text-secondary)' }}>Click any task to mark it complete. Your roadmap is regenerated automatically based on your latest scores.</p>
        </div>
    );
}
